### ISSUE TITLE
namedotcom_record does not support import

### ISSUE THREAD

**Issue by 387119** [lexfrei/terraform-provider-namedotcom#6]
```
[~/src/my/vs/dns/terraform]$ tf import namedotcom_record.dns_to_common_ip mydomain.com:1111111
namedotcom_record.dns_to_common_ip: Importing from ID "mydomain.com:111111"...
╷
│ Error: resource namedotcom_record doesn't support import
```

**Comment by 387119** [comment]
please validate https://github.com/lexfrei/terraform-provider-namedotcom/pull/7

**Comment by 387119** [comment]
```
[~/src/my/vs/dns/terraform]$ tf import namedotcom_record.dns_to_common_ip mydomain.com:111111
namedotcom_record.dns_to_common_ip: Importing from ID "mydomain.com:111111"...
namedotcom_record.dns_to_common_ip: Import prepared!
  Prepared namedotcom_record for import
namedotcom_record.dns_to_common_ip: Refreshing state... [id=11111]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by 387119** [comment]
since name.com can not search for record only by ID, (based on API we need domain_name) as well, so only way is to use compex ID = domain:id, either domain:host, in PR you can find active way "domain:id", as well as commented block for "domain:host" way.

we can either keep it as is, or leave only one preferred way, to your choose

**Comment by 387119** [comment]
@lexfrei  lexfrei

**Comment by 387119** [comment]
TODO: known issue
if you use for_each in resource namedotcom_record
if terraform.tfstate does not exists you cannot import records from the start.
- first import will be successful
- second import will fail with error "Error: Resource already managed by Terraform"

to prevent modifying state file manually, way that it will work with for_each is next
- generate terraform.tfstate file at least with one record (example: create test host)
- fullfill for_each variables
- import will work for all hosts now.

**Comment by lexfrei** [comment]
This #7 is merged now, awaitng for release

**Comment by lexfrei** [comment]
@387119 1.2.0 just released. Test it please and reopen if something went wrong.
